version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 173961276629.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build startedd on `date`
      - echo Building the Docker image...          
      - docker build -t container_app .
      - docker tag container_app:latest 173961276629.dkr.ecr.us-east-1.amazonaws.com/container_app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 173961276629.dkr.ecr.us-east-1.amazonaws.com/container_app:latest
artifacts:
  files:
    - '**/*'